# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

dist-name() {
 case $OSTYPE in
  darwin*)
        echo "darwin"
        ;;
  linux*)
        echo "linux"
        ;;
  *)
        echo "unknown"
        ;;
 esac
}

DIST="$(dist-name)"

[[ -f "${ZDOTDIR:-$HOME}/.$DIST.zshrc" ]] && source "${ZDOTDIR:-$HOME}/.$DIST.zshrc"

# Terminal config
export TERM="xterm-256color" 
export VISUAL=vim
export EDITOR="$VISUAL"

export OPT="/opt"

export zsh-history-fix() {
  mv ~/.zhistory ~/.zsh_history_corrupt
  strings ~/.zsh_history_corrupt > .zhistory
  fc -R ~/.zhistory
  rm ~/.zsh_history_corrupt
}

export export-env-file() {
  export $(cat ${@} | grep -v "#" | xargs)
}

export kube-delete-evicted() {
  kubectl get pods "${@}" -o json | jq '.items[] | select(.status.reason!=null) | select(.status.reason | contains("Evicted")) | "kubectl delete pods \(.metadata.name) -n \(.metadata.namespace)"' | xargs -n 1 bash -c
}

export kube-delete-kind() {
 kubectl get "$1" | grep "$2" | tr -s " " | cut -d " " -f1 | xargs kubectl delete "$1"
}

export edit() {
  $EDITOR $@
}

# Aliases
## xargs alias expansion
alias xargs="xargs "

## nocorrect is needed for zsh-autocomplete
# alias sudo='nocorrect sudo'

# GPG
export GPG_TTY=$(tty)

## Gron
### https://github.com/tomnomnom/gron
alias ungron="gron --ungron "

## ZSH

alias zp-edit="edit ${ZDOTDIR:-$HOME}/.zpreztorc "
alias zpe="zp-edit "
alias zsh-reload="source ${ZDOTDIR:-$HOME}/.zshrc "
alias zsh-edit="edit ~/.zshrc && zsh-reload "
alias zr="zsh-reload "
alias ze="zsh-edit "
alias zeos="edit ${ZDOTDIR:-$HOME}/.$DIST.zshrc"

alias zsh-edit-dist="edit ~/.$DIST.zshrc && zsh-reload "
alias zed="zsh-edit-dist " 

## XDG
alias xk=xkill

## Utils
alias sudo-chown-me="sudo chown -R $USER:$USER"
alias sudo-env="sudo --preserve-env "PATH=$PATH" $@"
alias md5-dir="find . -type f -exec md5sum {} \; | sort -k 2 | md5sum"
alias watch="watch "

## Git

alias git-del-merged="git branch -vv | grep 'origin/.*: gone]' | awk '{print \$1}' | xargs git branch -d"
alias git-del-merged-f="git branch -vv | grep 'origin/.*: gone]' | awk '{print \$1}' | xargs git branch -D"

# Kubernetes
alias k="kubectl"
alias kdk="kube-delete-kind "

export PATH=$PATH:/usr/local/kubebuilder/bin
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

# VVC
alias v="vvc"
if [ -x "$(which vvc)" ]; then
 [ ! -f ~/.zsh/completion/_vvc ] && vvc completion zsh > ~/.zsh/completion/_vvc
 autoload -Uz compinit
 compinit
fi


# AWS
# alias aws='docker run --rm -it -v ~/.aws:/root/.aws -v $(pwd):/aws amazon/aws-cli:${AWS_CLI_VERSION:-2.1.1}'

## eksctl
mkdir -p ~/.zsh/completion/
fpath=($fpath ~/.zsh/completion)

[ -x "$(which eksctl)" ] && [ ! -f ~/.zsh/completion/_eksctl ] && eksctl completion zsh > ~/.zsh/completion/_eksctl

# Python Poetry
[ -f $HOME/.poetry/env ] && source $HOME/.poetry/env

# Open Frameworks
export OF_ROOT=$HOME/Workspace/openFrameworks
export OF_PATH=$OF_ROOT
export PG_OF_PATH=$OF_ROOT

# BFG (Git history)
alias bfg="java -jar $OPT/bfg.jar"

# bazel
alias bazel="bazelisk "

# Asdf package manager
export ASDF_ROOT=$HOME/.asdf
export ASDF_INSTALLS=$ASDF_ROOT/installs
if [ -f $ASDF_ROOT/asdf.sh ]; then
source $ASDF_ROOT/asdf.sh
fpath=(${ASDF_ROOT}/completions $fpath)
autoload -Uz compinit && compinit
fi


# Processing
export PATH=$PATH:/opt/processing

# Java
#export JAVA_HOME="$(dirname $(dirname $(realpath $(which javac))))"
source ~/.asdf/plugins/java/set-java-home.zsh

# Golang
#GOV=$(asdf current golang | tr -s " " | cut -d " " -f2)
#export GOROOT=$ASDF_INSTALLS/golang/$GOV/go/

source ~/.asdf/plugins/golang/set-env.zsh
export GOPATH=$HOME/Workspace/go
export PATH=$PATH:$GOPATH/bin

# K8s

export KUBECONFIG=$HOME/.kube/config

# Ververica
export VV=$HOME/Workspace/ververica

# Local bin
export PATH=$HOME/bin:$PATH
export PATH=$HOME/.local/bin:$PATH

# Tokens eek
[[ -s $HOME/.tokens ]] && export-env-file $HOME/.tokens

# Shell

# p10k
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
#[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# starship
eval "$(starship init zsh)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/austin/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/austin/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/austin/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/austin/google-cloud-sdk/completion.zsh.inc'; fi
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
